services:

  app:
    build: 
      dockerfile: Dockerfile.app
    restart: on-failure
    ports:
      - ${APP_PORT}:8080
    environment:
      POSTGRES_URI: postgres://postgres:postgres@db:5432/shortify?sslmode=disable
      GIN_MODE: release
    depends_on:
      - db
    networks:
      - shortify-net

  db:
    image: postgres:16.2-alpine3.19
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shortify
    volumes:
      - shortify:/data/db
    networks:
      - shortify-net

  migrate:
    image: migrate/migrate
    networks:
      - shortify-net
    volumes:
      - ./database/migration:/database/migration
    command: ["-path", "/database/migration", "-database",  "postgres://postgres:postgres@db:5432/shortify?sslmode=disable", "up"]
    links: 
      - db

volumes:
  shortify:

networks:
  shortify-net:
    driver: bridge